apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger-loadtester
  namespace: cicd
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: flagger-loadtester
  chart:
    repository: https://flagger.app
    name: loadtester
    version: 0.14.0