apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: error-rate
spec:
  provider:
    type: prometheus
    address: "http://prometheus-server.istio-system.svc.cluster.local"
  query: |
    100 - sum(
      rate(
        nginx_ingress_controller_requests{
          ingress="{{ ingress }}",
          status!~"5.*"
        }[{{ interval }}]
      )
    ) 
    / 
    sum(
      rate(
        nginx_ingress_controller_requests{
          ingress="{{ ingress }}"
        }[{{ interval }}]
      )
    ) 
    * 100